/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simko;

/**
 *
 * @author Farhan Ariyanto
 */
public class beranda extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public beranda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblkamar = new javax.swing.JLabel();
        lblpenghuni = new javax.swing.JLabel();
        lbl_penghuni = new javax.swing.JLabel();
        lbl_kamar = new javax.swing.JLabel();
        lbl_tagihan = new javax.swing.JLabel();
        lbl_laporan = new javax.swing.JLabel();
        lbl_keluar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblnama1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        lblnama1.setForeground(new java.awt.Color(102, 102, 102));
        lblnama1.setText(".");
        getContentPane().add(lblnama1);
        lblnama1.setBounds(1750, 40, 130, 40);

        lblnama.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        lblnama.setForeground(new java.awt.Color(0, 153, 153));
        lblnama.setText(".");
        getContentPane().add(lblnama);
        lblnama.setBounds(1270, 580, 190, 50);

        lblkamar.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        lblkamar.setForeground(new java.awt.Color(0, 153, 153));
        lblkamar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblkamar.setText("10");
        lblkamar.setToolTipText("");
        getContentPane().add(lblkamar);
        lblkamar.setBounds(1270, 280, 170, 90);

        lblpenghuni.setFont(new java.awt.Font("Arial", 1, 80)); // NOI18N
        lblpenghuni.setForeground(new java.awt.Color(0, 153, 153));
        lblpenghuni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblpenghuni.setText("17");
        getContentPane().add(lblpenghuni);
        lblpenghuni.setBounds(740, 280, 160, 90);

        lbl_penghuni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_penghuniMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_penghuni);
        lbl_penghuni.setBounds(0, 340, 280, 50);

        lbl_kamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_kamarMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_kamar);
        lbl_kamar.setBounds(0, 420, 270, 50);

        lbl_tagihan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_tagihanMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_tagihan);
        lbl_tagihan.setBounds(0, 490, 270, 50);

        lbl_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_laporanMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_laporan);
        lbl_laporan.setBounds(0, 560, 280, 50);

        lbl_keluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_keluarMouseClicked(evt);
            }
        });
        getContentPane().add(lbl_keluar);
        lbl_keluar.setBounds(0, 960, 230, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Beranda.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbl_penghuniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_penghuniMouseClicked
        this.setVisible(false);
        new form_penghuni().setVisible(true);
    }//GEN-LAST:event_lbl_penghuniMouseClicked

    private void lbl_kamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_kamarMouseClicked
        this.setVisible(false);
        new form_kamar().setVisible(true);
    }//GEN-LAST:event_lbl_kamarMouseClicked

    private void lbl_tagihanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_tagihanMouseClicked
        this.setVisible(false);
        new form_tagihan().setVisible(true);
    }//GEN-LAST:event_lbl_tagihanMouseClicked

    private void lbl_laporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_laporanMouseClicked
        this.setVisible(false);
        new form_laporan().setVisible(true);
    }//GEN-LAST:event_lbl_laporanMouseClicked

    private void lbl_keluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_keluarMouseClicked
        this.setVisible(true);
        new popUp_keluar().setVisible(true);
    }//GEN-LAST:event_lbl_keluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(beranda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new beranda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_kamar;
    private javax.swing.JLabel lbl_keluar;
    private javax.swing.JLabel lbl_laporan;
    private javax.swing.JLabel lbl_penghuni;
    private javax.swing.JLabel lbl_tagihan;
    private javax.swing.JLabel lblkamar;
    public static final javax.swing.JLabel lblnama = new javax.swing.JLabel();
    public static final javax.swing.JLabel lblnama1 = new javax.swing.JLabel();
    private javax.swing.JLabel lblpenghuni;
    // End of variables declaration//GEN-END:variables
}
