/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simko;

import java.sql.Connection;
import javax.swing.JOptionPane;

/**
 *
 * @author Farhan Ariyanto
 */
public class frmregister extends javax.swing.JFrame {

    /**
     * Creates new form frmregistes
     */
    public frmregister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtfnik = new javax.swing.JTextField();
        txtfnama = new javax.swing.JTextField();
        txtfusername = new javax.swing.JTextField();
        txtfpassword = new javax.swing.JPasswordField();
        lbldaftar = new javax.swing.JLabel();
        lbllogin = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtfnik.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtfnik.setBorder(null);
        txtfnik.setOpaque(false);
        getContentPane().add(txtfnik);
        txtfnik.setBounds(1020, 330, 550, 60);

        txtfnama.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtfnama.setBorder(null);
        txtfnama.setOpaque(false);
        txtfnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfnamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtfnama);
        txtfnama.setBounds(1020, 460, 560, 60);

        txtfusername.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        txtfusername.setBorder(null);
        txtfusername.setOpaque(false);
        getContentPane().add(txtfusername);
        txtfusername.setBounds(1030, 590, 550, 60);

        txtfpassword.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtfpassword.setBorder(null);
        txtfpassword.setOpaque(false);
        getContentPane().add(txtfpassword);
        txtfpassword.setBounds(1030, 720, 540, 60);

        lbldaftar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldaftarMouseClicked(evt);
            }
        });
        getContentPane().add(lbldaftar);
        lbldaftar.setBounds(1150, 830, 300, 90);

        lbllogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblloginMouseClicked(evt);
            }
        });
        getContentPane().add(lbllogin);
        lbllogin.setBounds(190, 600, 310, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Buat Akun.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1920, 1080);

        setSize(new java.awt.Dimension(1938, 1127));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblloginMouseClicked
        this.setVisible(false);
        new frmlogin().setVisible(true);
    }//GEN-LAST:event_lblloginMouseClicked

    private void txtfnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfnamaActionPerformed

    private void lbldaftarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldaftarMouseClicked
        try {
            String sql = "INSERT INTO tb_login VALUES ('"+txtfnik.getText()
                    +"','"+txtfnama.getText()
                    +"','"+txtfusername.getText()
                    +"','"+txtfpassword.getText()+"')";
            java.sql.Connection conn=(Connection)config.configDB();
            java.sql.PreparedStatement pst=conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Register telah berhasil");
            this.setVisible(false);
            new frmlogin().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lbldaftarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmregister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmregister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbldaftar;
    private javax.swing.JLabel lbllogin;
    private javax.swing.JTextField txtfnama;
    private javax.swing.JTextField txtfnik;
    private javax.swing.JPasswordField txtfpassword;
    private javax.swing.JTextField txtfusername;
    // End of variables declaration//GEN-END:variables
}
